export const TRANSLATIONS = {
    en_US: {
      Login: 'Login',
      Forgot_password: 'Forgot Password',
      Password: 'Password',
      Dashboard: 'Dashboard',
      Projects: 'Projects',
      Taken: 'Taken',
      Hours: 'Hours',
      Management: 'Management',
      Users: 'Users',
      Hours_off: 'Hours off',
      Enter_hours: 'Enter hours',
      Approve_hours: 'Approve hours',
      Role: 'Role',
      Purchase: 'Purchase',
      Exploitation: 'Exploitation',
      Coverage: 'Coverage',
      Staff_members: 'Staff members',
      Activities: 'Activities',
      Zeno: 'Zeno',
      Audit: 'Audit',
      Consistency_control: 'Consistency control',
      Adjust: 'Adjust',
      Tags: 'Tags',
      Tag_groups: 'Tag groups',
      Documents: 'Documents',
      Profile: 'Profile',
      Change_password: 'Change password',
      LogOut: 'LogOut',
      New_user: 'New user',
      UserName: 'UserName',
      Email: 'Email',
      Active: 'Active',
      Action: 'Action',
      Previous:'Previous',
      Next:'Next',
      Show_entries:'Show entries',
      Show:'Show',
      Entries:'entries',
      Show_page:'Showing page',
      Add_new_role: 'Add new role',
      Description: 'Description',
      CoverItem: 'CoverItem',
      Items: 'Items',
      Add_new_purchase: 'Add new purchase',
      Add_new_exploitation_rule: 'Add new exploitation rule',
      Percentage: 'Percentage',
      Add_new_staffmember: 'Add new staff member',
      LastName: 'Lastname',
      FirstName: 'FirstName',
      Employee_number: 'Number',
      DateService: 'DateService',
      Direct: 'Direct',
      Date_out_of_service: 'DateOutService',
      Email_address: 'Email address',
      Save: 'Save',
      Confirm_password: 'Confirm Password',
      Edit_user: 'Edit User',
      New_role: 'New Role',
      HourType: 'HourType',
      Select: 'Select...',
      CoverArticle: 'CoverArticle',
      Edit_role: 'Edit Role',
      New_rate: 'New Rate',
      PriceCost: 'PriceCost',
      Price: 'Price',
      FinancialYear: 'FinancialYear',
      Edit_rate: 'Edit Rate'
    },

    nl_BE: {
      Login: 'Inloggen',
      Forgot_password: 'Forgot Password',
      Password: 'Wachtwoord',
      Dashboard: 'Dashboard',
      Projects: 'Projecten',
      Taken: 'Taken',
      Management: 'Beheer',
      Hours: 'Uren', 
      Users: 'Gebruikers',
      Hours_off: 'Afkenuren uren',
      Enter_hours: 'Uren invoeren',
      Approve_hours: 'Uren goedkeuren',
      Roll: 'Rollen',
      Purchase: 'Inkoop',
      Exploitation: 'Exploitatie',
      Coverage: 'Dekking',
      Staff_members: 'Medewerkers',
      Activities: 'Activiteiten',
      Zeno: 'Zeno',
      Audit: 'Audit',
      Consistency_control: 'Consistentie controle',
      Adjust: 'Instelligen',
      Tags: 'Tags',
      Tag_groups: 'Tag groups',
      Documents: 'Documenten',
      Profile: 'Profiel',
      Change_password: 'Verandering wachtwoord',
      LogOut: 'LogUit',
      UserName: 'Gebruiker Naam',
      Email: 'Email',
      Active: 'Actief',
      Role: 'Rol',
      Action: 'Actie',
      Previous:'Voorgaand',
      Next:'Volgende',
      Show_entries:'Toon vermeldingen',
      Show:'Laten zien',
      Entries:'entries',
      Show_page:'Pagina weergegeven',
      Add_new_role: 'Voeg Nieuwe rol toe',
      Description: 'Omschrijving',
      CoverItem: 'Dekkingsartikel',
      Items: 'Artikel',
      Add_new_purchase : 'Voeg Nieuwe inkoop toe',
      Add_new_exploitation_rule: 'Voeg nieuwe exploitatie regel',
      Percentage: 'Percentage',
      Add_new_staffmember: 'Voeg nieuwe medewerker',
      LastName: 'Achternaam',
      FirstName: 'Voornaam',
      Employee_number: 'Nummer',
      DateService: 'Datumindienst',
      Direct: 'Direct',
      Date_out_of_service: 'Datumuitdienst',
      New_user: 'Nieuwe Gebruiker',
      Email_address: 'Email adres',
      Save: 'Opslaan',
      Confirm_password: 'Bevestig Wachtwoord',
      Edit_user: 'Bewerk Gebruiker',
      New_role: 'Nieuwe Rol',
      HourType: 'Uursoort',
      Select: 'Kiezen',
      CoverArticle: 'DekkingsArtikel',
      Edit_role: 'Edit Rolls',
      New_rate: 'Nieuwe Tarief',
      PriceCost: 'Kostprijs',
      Price: 'Prijs',
      FinancialYear: 'Boekjaar',
      Edit_rate: 'Bewerk Tarief'
    }
  };