export const TRANSLATIONS = {
    en_US: {
      Login: 'Login',
      Forgot_password: 'Forgot Password',
      Password: 'Password',
      Dashboard: 'Dashboard',
      Projects: 'Projects',
      Taken: 'Taken',
      Hours: 'Hours',
      Management: 'Management',
      Users: 'Users',
      Hours_off: 'Hours off',
      Enter_hours: 'Enter hours',
      Approve_hours: 'Approve hours',
      Role: 'Role',
      Purchase: 'Purchase',
      Exploitation: 'Exploitation',
      Coverage: 'Coverage',
      Staff_members: 'Staff',
      Activities: 'Activities',
      Zeno: 'Zeno',
      Audit: 'Audit',
      Consistency_control: 'Consistency control',
      Settings: 'Settings',
      Tags: 'Tags',
      Tag_groups: 'Tag groups',
      Documents: 'Documents',
      Profile: 'Profile',
      Change_password: 'Change password',
      LogOut: 'LogOut',
      New_user: 'New user',
      UserName: 'UserName',
      Email: 'Email',
      Active: 'Active',
      Action: 'Action',
      Previous:'Previous',
      Next:'Next',
      Show_entries:'Show entries',
      Show:'Show',
      Entries:'entries',
      Show_page:'Showing page',
      Add_new_role: 'Add new role',
      Description: 'Description',
      CoverItem: 'CoverItem',
      Items: 'Items',
      Add_new_purchase: 'Add new purchase',
      Add_new_exploitation_rule: 'Add new exploitation rule',
      Percentage: 'Percentage',
      Add_new_staffmember: 'Add new staff member',
      LastName: 'Lastname',
      FirstName: 'FirstName',
      Employee_number: 'Number',
      DateService: 'DateService',
      Direct: 'Direct',
      Date_out_of_service: 'DateOutService',
      Email_address: 'Email address',
      Save: 'Save',
      Confirm_password: 'Confirm Password',
      Edit_user: 'Edit User',
      New_role: 'New Role',
      HourType: 'HourType',
      Select: 'Select...',
      CoverArticle: 'CoverArticle',
      Edit_role: 'Edit Role',
      New_rate: 'New Rate',
      PriceCost: 'PriceCost',
      Price: 'Price',
      FinancialYear: 'FinancialYear',
      Edit_rate: 'Edit Rate',
      New_purhcase: 'New Purchase',
      Edit_purhcase: 'Edit Purchase',
      Article: 'Article',
      New_exploitation: 'New Exploitation',
      Link_zeno_article: 'Link Zeno Article',
      Edit_exploitation: 'Edit Exploitation',
      Revised_percentage: 'Revised Percentage',
      Edit_coverage: 'Edit Coverage',
      New_Staff_member: 'New Staff Member',
      Staff_number: 'StaffNumber',
      Hours_per_week: 'Hours per week',
      New_norm_hours: 'New Norm Hours',
      Year: 'Year',
      NormHours: 'NormHours',
      Main_Role: 'MainRole',
      Starting_date: 'StartingDate',
      EndDate: 'EndDate',
      Revenue: 'Revenue',
      Productivity: 'Productivity',
      Edit_norm_hours: 'Edit Nrom Hours',
      Start_Date: 'Start Date',
      The_norm_hour_has_been_deleted: 'The norm hour has been deleted!',
      The_staff_has_been_deleted: 'The staff has been deleted!',
      Password_change: 'Password Change',
      Old_password: 'Old password',
      New_password: 'New password',
      Confirm_newpassword: 'Confirm new password',
      Value: 'Value',
      Add_new_activity: 'Add new activity',
      New_activity: 'New activity',
      Enter_email: 'Enter your email address',
      Sucess_email: 'An email has been sent to the registered email address. Follow the instructions in the email to change your password',
      Unlinked_articles: 'Show unlinked articles',
      Reset_password: 'Reset Password',
      ArticleGroup: 'ArticleGroup',
      ZenoArticle: 'ZenoArticle',
      Table: 'Table',
      Field: 'Field',
      OldValue: 'OldValue',
      NewValue: 'NewValue',
      ChangedBy: 'ChangedBy',
      ModifiedOn: 'ModifiedOn',
      Type: 'Type',
      Edit_activity: 'Edit Activity',
      Label: 'Label',
      Edit_setting: 'Edit Setting',
      Group: 'Group',
      Add_new_taggroup: 'Add new tag group',
      New_taggroup: 'New Tag Groop',
      TagGroup: 'TagGroup',
      New_tag: 'New Tag',
      Edit_tag: 'Edit Tag',
      Add_new_tag: 'Add new tag',
      Project: 'Project',
      Document: 'Document',
      Documenttype: 'Documenttype',
      Add_new_document: 'Add new document',
      New_Document: 'New Document',
      File: 'File',
      Choose_File: 'Choose File',
      Name: 'Name',
      Projectcode: 'Projectcode',
      Financial_year: 'FinancialYear',
      Relationship: 'Relationship',
      Project_led: 'Projectled',
      File_upload_faile: 'File upload faile!',
      All_hours: 'All hours',
      End_date: 'End Date',
      Reject: 'Reject',
      Date: 'Date',
      Week: 'Week',
      Status: 'Status',
      EnterHours: 'Enter Hours',
      Show_weeks_submitted: 'Show weeks not fully submitted'
    },

    nl_BE: {
      Login: 'Inloggen',
      Forgot_password: 'Forgot Password',
      Password: 'Wachtwoord',
      Dashboard: 'Dashboard',
      Projects: 'Projecten',
      Taken: 'Taken',
      Management: 'Beheer',
      Hours: 'Uren', 
      Users: 'Gebruikers',
      Hours_off: 'Afkenuren uren',
      Enter_hours: 'Uren invoeren',
      Approve_hours: 'Uren goedkeuren',
      Roll: 'Rollen',
      Purchase: 'Inkoop',
      Exploitation: 'Exploitatie',
      Coverage: 'Dekking',
      Staff_members: 'Medewerkers',
      Activities: 'Activiteiten',
      Zeno: 'Zeno',
      Audit: 'Audit',
      Consistency_control: 'Consistentie controle',
      Settings: 'Instelligen',
      Tags: 'Tags',
      Tag_groups: 'Tag groups',
      Documents: 'Documenten',
      Profile: 'Profiel',
      Change_password: 'Verandering wachtwoord',
      LogOut: 'LogUit',
      UserName: 'Gebruiker Naam',
      Email: 'Email',
      Active: 'Actief',
      Role: 'Rol',
      Action: 'Actie',
      Previous:'Voorgaand',
      Next:'Volgende',
      Show_entries:'Toon vermeldingen',
      Show:'Laten zien',
      Entries:'entries',
      Show_page:'Pagina weergegeven',
      Add_new_role: 'Voeg Nieuwe rol toe',
      Description: 'Omschrijving',
      CoverItem: 'Dekkingsartikel',
      Items: 'Artikel',
      Add_new_purchase : 'Voeg Nieuwe inkoop toe',
      Add_new_exploitation_rule: 'Voeg nieuwe exploitatie regel',
      Percentage: 'Percentage',
      Add_new_staffmember: 'Voeg nieuwe medewerker',
      LastName: 'Achternaam',
      FirstName: 'Voornaam',
      Employee_number: 'Nummer',
      DateService: 'Datumindienst',
      Direct: 'Direct',
      Date_out_of_service: 'Datumuitdienst',
      New_user: 'Nieuwe Gebruiker',
      Email_address: 'Email adres',
      Save: 'Opslaan',
      Confirm_password: 'Bevestig Wachtwoord',
      Edit_user: 'Bewerk Gebruiker',
      New_role: 'Nieuwe Rol',
      HourType: 'Uursoort',
      Select: 'Kiezen',
      CoverArticle: 'DekkingsArtikel',
      Edit_role: 'Edit Rolls',
      New_rate: 'Nieuwe Tarief',
      PriceCost: 'Kostprijs',
      Price: 'Prijs',
      FinancialYear: 'Boekjaar',
      Edit_rate: 'Bewerk Tarief',
      New_purhcase: 'Nieuwe Inkoop',
      Edit_purhcase: 'Bewerk Inkoop',
      Article: 'Artikel',
      New_exploitation: 'Nieuwe Exploitatie',
      Link_zeno_article: 'Zeno artikel koppelen',
      Edit_exploitation: 'Bewerk Exploitatie',
      Revised_percentage: 'Herziene Percentage',
      Edit_coverage: 'Bewerk Dekking',
      New_Staff_member: 'Nieuwe Medewerker',
      Staff_number: 'PersoneelsNummer',
      Hours_per_week: 'Uren per week',
      New_norm_hours: 'Nieuwe Norm Uren',
      Year: 'Jaar',
      NormHours: 'NormUren',
      Starting_date: 'BeginnendDatum',
      EndDate: 'EindeDatum',
      Revenue: 'Omzet',
      Productivity: 'Produktiviteit',
      Main_Role: 'HoofdRol',
      Edit_norm_hours: 'Bewerk Norm Uren',
      Start_Date: 'Begin Datum',
      The_norm_hour_has_been_deleted: 'Het normuur is verwijderd!',
      The_staff_has_been_deleted: 'Het personeel is verwijderd',
      Password_change: 'Wachtwoord Verandering',
      Old_password: 'Oud wachtwoord',
      New_password: 'Nieuwe Wachtwoord',
      Confirm_newpassword: 'Bevestigen nieuwe wachtwoord',
      Value: 'Waarde',
      Add_new_activity: 'Toevoegen nieuwe werkzaamheid',
      New_activity: 'Nieuwe werkzaamheid',
      Enter_email: 'Vul uw e-mailadres in',
      Sucess_email: 'Er is een email verzonden naar het geregistreerde emailadres. Volg de instructies in de email om uw wachtwoord aan te passen',
      Unlinked_articles: 'Toon niet gekoppelde artikelen',
      Reset_password: 'Reset Wachtwoord',
      ArticleGroup: 'ArtikelGroep',
      ZenoArticle: 'ZenoArtikel',
      Table: 'Tafel',
      Field: 'Veld',
      OldValue: 'OudWaarde',
      NewValue: 'NieuweWaarde',
      ChangedBy: 'VeranderdDoor',
      ModifiedOn: 'GewijzigdOp',
      Type: 'Type',
      Edit_activity: 'Bewerk Werkzaamheid',
      Label: 'Label',
      Edit_setting: 'Bewerk Instelligen',
      Group: 'Groep',
      Add_new_taggroup: 'Toevoegen nieuwe tag groep',
      New_taggroup: 'Nieuwe Tag Groep',
      TagGroup: 'TagGroep',
      New_tag: 'Nieuw Tag',
      Edit_tag: 'Bewerk Tag',
      Add_new_tag: 'Toevoegen Nieuwe Tag',
      Project: 'Project',
      Document: 'Document',
      Documenttype: 'Documenttype',
      Add_new_document: 'Toevoegen nieuwe document',
      New_Document: 'Nieuwe Document',
      File: 'Bestand',
      Choose_File: 'Kiezen Bestand',
      Name: 'Naam',
      Projectcode: 'Projectcode',
      Financial_year: 'Boekjaar',
      Relationship: 'Relatie',
      Project_led: 'Projectleide',
      File_upload_faile: 'Bestand uploaden mislukt!',
      All_hours: 'All hours',
      End_date: 'Einddatum',
      Reject: 'Afwijzen',
      Date: 'Datum',
      Week: 'Week',
      Status: 'Staat',
      EnterHours: 'Uren invoeren',
      Show_weeks_submitted: 'Toon weken niet volledig ingediend'
    }
  };