export const TRANSLATIONS = {
    en_US: {
      Username: 'Username',
      Password: 'Password',
      Forgot_password: 'Forgot password?',
      Sign_in: 'Sign in',
      Search:'Search',
      Products:'Products',
      Add_Product:'Add Product',
      Dashboard:'Dashboard',
      Sales_Order:'Sales Order',
      Purchase_Order:'Purchase Order',
      Supplier:'Supplier',
      Customer:'Customer',
      Product_Group:'Product Group',
      Sales_Unit:'Sales Unit',
      Kilogram:'Kilogram',
      Product:'Product',
      Productcode:'Productcode',
      Previous:'Previous',
      Next:'Next',
      Show_entries:'Show entries',
      Show:'Show',
      Entries:'entries',
      Show_page:'Showing page',
      Producttype: 'Producttype',
      Concentration: 'Concentration',
      Addition: 'Addition',
      Description: 'Description',
      Salesunit: 'Salesunit',
      Partial: 'Partial',
      Intrastat: 'Intrastat',
      Save: 'Save',
      User: 'User',
      Add_User: 'Add User',
      FirstName: 'FirstName',
      LastName: 'LastName',
      Email: 'Email',
      Active: 'Active',
      State: 'State',
      View_User: 'View User',
      Edit_User: 'Edit User',
      UserName: 'UserName',
      Roles: 'Roles',
      ConfirmPassword: 'ConfirmPassword',
      PhoneNumber: 'PhoneNumber',
      IsActive: 'IsActive',
      Product_Details: 'Product Details',
      Productgroup: 'Productgroup',
      Purchase_Price: 'Purchase Price',
      Price: 'Price',
      Start_date: 'Start date',
      End_date: 'End date',
      Add_Purchase_Price: 'Add Purchase Price',
      Sales_Price: 'Sales Price',
      Add_Salese_Price: 'Add Salese Price',
      Transport_Price: 'Transport Price',
      Id: 'Id',
      Transporter: 'Transporter',
      Pricingtype: 'Pricingtype',
      Add_Transport_Price: 'Add Transport Price',
      Add_Sales_Order: 'Add Sales Order',
      Reference: 'Reference',
      Order_Date: 'Order Date',
      Total_amount: 'Total amount',
      Sales_Order_Details: 'Sales Order Details',
      Loading_Date: 'Loading Date',
      Quantity: 'Quantity',
      Amount: 'Amount',
      Add_Pursase_Order: 'Add Pursase Order',
      Invoice: 'Invoice',
      Invoice_date: 'Invoice date',
      Journal: 'Journal',
      Expiration_Date: 'Expiration Date',
      Purchase_Order_Details: 'Purchase Order Details',
      Add_row: 'Add row',
      GlCode: 'GlCode',
      VATCode: 'VATCode',
      VATAmount: 'VATAmount',
      Reporting_Date: 'Reporting Date',
      Purchase_Unit: 'Purchase Unit',
      Approver: 'Approver',
      Add_Price: 'Add Price',
      Copy_Product: 'Copy Product',
      Select: 'Select...',
      Task: 'Task',
      Task_Overview: 'Task Overview',
      Tasktype: 'Tasktype',
      Subject: 'Subject',
      TaskStatus: 'TaskStatus',
      Action: 'Action',
      Edit_Task: 'Edit Task',
      Add_Task: 'Add Task',
      Approve: 'Approve',
      Customer_Note: 'Customer Note'
    },


    nl_BE: {
      Username: 'Gebruikersnaam',
      Password: 'Wachtwoord',
      Forgot_password: 'Wachtwoord vergeten?',
      Sign_in: 'Aanmelden',
      Search:'Zoeken',
      Products:'Producten',
      Add_Product:'Toevoegen Product',
      Dashboard:'Dashboard',
      Sales_Order:'Verkoop Bestellen',
      Purchase_Order:'Aankoop Bestelling',
      Supplier:'Leverancier',
      Customer:'Klant',
      Product_Group:'Productgroep',
      Sales_Unit:'Verkoop eenheid',
      Kilogram:'Kilogram',
      Product:'Product',
      Productcode:'Productcode',
      Previous:'Voorgaand',
      Next:'Volgende',
      Show_entries:'Toon vermeldingen',
      Show:'Laten zien',
      Entries:'entries',
      Show_page:'Pagina weergegeven',
      Producttype: 'Producttype',
      Concentration: 'Concentratie',
      Addition: 'toevoeging',
      Description: 'Omschrijving',
      Salesunit: 'Salesunit',
      Partial: 'Partieel',
      Intrastat: 'Intrastat',
      Save: 'Obslaan',
      User: 'Gebruiker',
      Add_User: 'Voeg gebruiker toe',
      FirstName: 'Voornaam',
      LastName: 'Achternaam',
      Email: 'Email',
      Active: 'Actief',
      State: 'Staat',
      View_User: 'Bekijk Gebruiker',
      Edit_User: 'Bewerk Gebruiker',
      UserName: 'Gebruikersnaam',
      Roles: 'Rollen',
      ConfirmPassword: 'Bevestig Wachtwoord',
      PhoneNumber: 'Telefoonnummer',
      IsActive: 'Is Actief',
      Product_Details: 'Product Details',
      Productgroup: 'Productgroep',
      Purchase_Price: 'Aankoopprijs',
      Price: 'Prijs',
      Start_date: 'Begin date',
      End_date: 'Einde date',
      Add_Purchase_Price: 'Aankoopprijs toevoegen',
      Sales_Price: 'Verkoopprijs',
      Add_Salese_Price: 'Voeg  Verkoopprijs',
      Transport_Price: 'Transportprijs',
      Id: 'Id',
      Transporter: 'Transporter',
      Pricingtype: 'Prijstype',
      Add_Transport_Price: 'Voeg transportprijs toe',
      Add_Sales_Order: 'Klantorder toevoegen',
      Reference: 'Referenie',
      Order_Date: 'Besteldatum',
      Total_amount: 'Totaalbedrag',
      Sales_Order_Details: 'Verkoop Bestellen Details',
      Loading_Date: 'Laaddatum',
      Quantity: 'Aantal stuks',
      Amount: 'Bedrag',
      Add_Pursase_Order: 'Toevoegen Pursase Bestellen',
      Invoice: 'Factuur',
      Invoice_date: 'Factuur date',
      Journal: 'Dagboek',
      Expiration_Date: 'vervaldatum',
      Purchase_Order_Details: 'Pursase Bestellen Details',
      Add_row: 'Rij toevoegen',
      GlCode: 'GlCode',
      VATCode: 'Btw nummer',
      VATAmount: 'Vattament',
      Reporting_Date: 'Balansdatum',
      Purchase_Unit: 'Aankoopeen heid',
      Approver: 'Approver',
      Add_Price: 'Prijs toevoegen',
      Copy_Product: 'Product kopiëren',
      Select: 'Selecteer...',
      Task: 'Taak',
      Task_Overview: 'Taak Overzicht',
      Tasktype: 'Taaktype',
      Subject: 'Onderwerpen',
      TaskStatus: 'Taakstaat',
      Action: 'Actie',
      Edit_Task: 'Bewerk Taak',
      Add_Task: 'Toevoegen Taak',
      Approve: 'Goedkeuren',
      Customer_Note: 'Klant Notitie'
    }
  };