const BASEURL = 'https://app-test.organisatie.freepeat.com';
export default {
    GetToken: "https://app-test.organisatie.freepeat.com/token",
    GetUserData: `${BASEURL}/api/users/GetUsers?excludeActiveUsers=false`,
    PostUserData: `${BASEURL}/api/Users`,
    DeleteUserData: `${BASEURL}/api/Users/`,
    GetUserDataById: `${BASEURL}/api/Users/`,
    PostUserUpdate: `${BASEURL}/api/Users`,
    PostProductData: `${BASEURL}/api/factory/execute/Appmakerz-Test/postProduct`,
    PostCopyProduct: `${BASEURL}/api/factory/execute/Appmakerz-Test/copyProduct`,
    GetProductData: `${BASEURL}/api/factory/execute/Appmakerz-Test/getProducts`,
    GetSupplierList: `${BASEURL}/api/factory/execute/Exact-Test/getSuppliersDropdown`,
    GetProductType: `${BASEURL}/api/factory/execute/Appmakerz-Test/getProductTypesDropdown`,
    GetSalesUnit: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesUnitsDropdown`,
    GetProductGroup: `${BASEURL}/api/factory/execute/Appmakerz-Test/getProductGroupsDropdown`,
    GetUnitData: `${BASEURL}/api/factory/execute/Exact-Test/getUnitsDropdown`,
    GetSalesData: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesOrders`,
    GetCustomerData: `${BASEURL}/api/factory/execute/Exact-Test/getCustomersDropdown`,
    PostSalesOrder: `${BASEURL}/api/factory/execute/Appmakerz-Test/postSalesOrder`,
    GetSalesDetail: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesOrder`,
    GetSalesItems: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesItemsDropdown`,
    GetSalesItemsPrice: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesPrice`,
    PostSalesOrderLine: `${BASEURL}/api/factory/execute/Appmakerz-Test/postSalesOrderLine`,
    GetSalesOrderLines: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesOrderLines`,
    GetSuppliersDropdown: `${BASEURL}/api/factory/execute/Exact-Test/getSuppliersDropdown`,
    GetJournalsDropdown: `${BASEURL}/api/factory/execute/Exact-Test/getJournalsDropdown`,
    PostPurchaseOrder: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseOrder`,
    GetPurchaseOrders: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseOrders`,
    GetPurchaseOrder: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseOrder`,
    GetPurchaseItems: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseItemsDropdown`,
    GetGlCode: `${BASEURL}/api/factory/execute/Exact-Test/getGlCodeDropdown`,
    GetVATCode: `${BASEURL}/api/factory/execute/Exact-Test/getVATCodeDropdown`,
    GetPurchasePrice: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchasePrice`,
    PostPurchaseOrderLine: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPurchaseOrderLine`,
    GetPurchaseOrderLines: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchaseOrderLines`,
    GetTransportPrice: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTransportPrices`,
    PostPricechangeTask: `${BASEURL}/api/factory/execute/Appmakerz-Test/postPricechangeTask`,
    GetTasks: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTasks`,
    GetTaskById: `${BASEURL}/api/factory/execute/appmakerz-test/getTaskById`,
    GetTasktypeDropdown: `${BASEURL}/api/factory/execute/appmakerz-test/getTasktypeDropdown`,
    GetTaskstatusDropdown: `${BASEURL}/api/factory/execute/appmakerz-test/getTaskstatusDropdown`,
    GetProductsDropdown: `${BASEURL}/api/factory/execute/appmakerz-test/getProductsDropdown`,
    GetUsersDropdown: `${BASEURL}/api/factory/execute/appmakerz-test/getUsersDropdown`,
    PutTask: `${BASEURL}/api/factory/execute/appmakerz-test/putTask`,
    ApprovePurchasePrice: `${BASEURL}/api/factory/execute/appmakerz-Test/ApprovePurchasePrice`,
    GetProduct: `${BASEURL}/api/factory/execute/Appmakerz-Test/getProduct`,
    GetPurchasePrices: `${BASEURL}/api/factory/execute/Appmakerz-Test/getPurchasePrices`,
    GetSalesPrices: `${BASEURL}/api/factory/execute/Appmakerz-Test/getSalesPrices`,
    GetTransportPrices: `${BASEURL}/api/factory/execute/Appmakerz-Test/getTransportPrices`,
    ApproveSalesPrice : `${BASEURL}/api/factory/execute/Appmakerz-Test/ApproveSalesPrice`,
    ApproveTransportPrice : `${BASEURL}/api/factory/execute/Appmakerz-Test/ApproveTransportPrice`,
  };
  
  
  